global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "python-core"
    metrics_path: /metrics
    static_configs:
      - targets: ["python-core:8000"]

  - job_name: "elixir-edge"
    metrics_path: /metrics
    static_configs:
      - targets: ["elixir-edge:4000"]

  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]
