super_admins:
- email: maruthi@turing.com
  name: Maruthi
- email: tyler@turing.com
  name: Tyler
admins: []
pods:
  alpha:
    name: Team Alpha
    reviewer:
      email: reviewer_a@turing.com
      name: Reviewer A
    trainers:
    - trainer1@turing.com
    - trainer2@turing.com
    - trainer3@turing.com
    - trainer4@turing.com
    - trainer5@turing.com
  beta:
    name: Team Beta
    reviewer:
      email: reviewer_b@turing.com
      name: Reviewer B
    trainers:
    - trainer6@turing.com
    - trainer7@turing.com
    - trainer8@turing.com
    - trainer9@turing.com
    - trainer10@turing.com
